import type { Metadata } from "next";
import { Geist, Geist_Mono, Raleway, Outfit } from "next/font/google";
import "./globals.css";
import Header from '@/component/header/Header';

import Footer from "@/component/footer/Footer";
import Preheader from "@/component/header/Preheader"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={`${geistSans.variable} ${geistMono.variable} ${raleway.variable} ${outfit.variable} antialiased`}
     >
<div className="max-w-full mx-auto px-4 sm:px-6 lg:px-8">
    <Preheader></Preheader>
        <Header></Header>
  
      
        {children}

       <Footer></Footer>
</div>


      </body>
    </html>
  );
}
